default: &default
  adapter: mysql2 # mysql2に接続するための設定
  encoding: utf8mb4 # 日本語も含めた全ての文字を扱うための設定。mysql専用の設定
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 'password'
  host: db
  port: 3306

development:
  <<: *default
  database: samplerails_development

test:
  <<: *default
  database: samplerails_test

production:
  <<: *default
  adapter: postgresql # postgresqlに接続するための設定
  encoding: unicode # 日本語も含めた全ての文字を扱うための設定
  url: <%= ENV['DATABASE_URL'] %> # 環境変数DATABASE_URLを参照して接続するための設定。Render.comでデプロイする際に使用する
